

version: 2

models:
  - name: example_model
    description: "Un modèle de test simple avec une ligne"
    columns:
      - name: id
        description: "L'identifiant de la ligne"
        tests:
          - not_null
          - unique

      - name: name
        description: "Le nom de test"
        tests:
          - not_null

