version: 2

sources:
  - name: music_source
    database: MUSIC_DB
    schema: PUBLIC
    tables:
      - name: album1
      - name: artist1
      - name: genre1
      - name: track1
      - name: mediatype1
      - name: playlist1
      - name: playlisttrack1

